---
title: "02 Supervised ML"
date: "2024-05-06"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Supervised ML - Regression

Last compiled: `r Sys.Date()`

```{r ml, fig.height=12, fig.width=10}
library(tidyverse)
library(parsnip)
library(recipes)
library(rsample)
library(yardstick)
library(rpart.plot)
library(workflows)

#Gathering Data----

bike_features_tbl <- readRDS("bike_features_tbl.rds")

bike_features_tbl <- bike_features_tbl %>% 
  select(model:url, `Rear Derailleur`, `Shift Lever`)


set.seed(seed = 1234)

#I. Build a model
model_linear_lm <- linear_reg(mode = "regression") %>%
  set_engine("lm")


#II. Create features with the recipes package
split_obj <- rsample::initial_split(bike_features_tbl, prop = 0.80,strata = category_2 )

train_tbl <- training(split_obj)
test_tbl  <- testing(split_obj)

train_tbl <- train_tbl %>% set_names(str_replace_all(names(train_tbl), " |-", "_"))
test_tbl  <- test_tbl  %>% set_names(str_replace_all(names(test_tbl),  " |-", "_"))


price_recipe <- recipe(price~ category_2 + frame_material + Rear_Derailleur + Shift_Lever , data = train_tbl)%>%
  step_novel(all_predictors(), -all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes())%>%
  step_nzv(all_predictors())

prepped_recipe <- prep(price_recipe, training = train_tbl) # NOT NEEDED (INCLUDED IN WORKLFOW) BUT ADDING FOR THE SAKE OF TASK #
train_recipe <- bake(prepped_recipe, train_tbl) # NOT NEEDED (INCLUDED IN WORKLFOW) BUT ADDING FOR THE SAKE OF TASK #
test_recipe <- bake(prepped_recipe, test_tbl)  # NOT NEEDED (INCLUDED IN WORKLFOW) BUT ADDING FOR THE SAKE OF TASK #

#III. Bundle the model and recipe with the workflow package

bikes_wflow <- 
  workflow() %>% 
  add_model(model_linear_lm) %>% 
  add_recipe(price_recipe)

model_linear_lm <-
  bikes_wflow %>% fit(data = train_tbl) 


#IV. Evaluate your model with the yardstick package

calc_metrics <- function(model, new_data = test_recipe) {
  model %>%
    predict(new_data = new_data) %>%
    
    bind_cols(new_data %>% select(price)) %>%
    yardstick::metrics(truth = price, estimate = .pred)
  
}

model_linear_lm %>% calc_metrics(test_tbl)

#Extra Plotting for Fun
model_linear_lm %>%
  broom::tidy() %>%
  arrange(p.value) %>%
  mutate(term = as_factor(term) %>% fct_rev()) %>%
  ggplot(aes(x = estimate, y = term)) +
  geom_point(color = "#2dc6d6", size = 3) +
  ggrepel::geom_label_repel(aes(label = scales::dollar(estimate, accuracy = 1, suffix = " €", prefix = "")),
                            size = 4, fill = "#272A36", color = "white") +
  scale_x_continuous(labels = scales::dollar_format(suffix = " €", prefix = "")) +
  labs(title = "Linear Regression: Feature Importance",
       subtitle = "Model 01: Simple lm Model") 

```