---
title: "05 LIME"
date: "2024-13-06"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Black-Box Models with LIME

Last compiled: `r Sys.Date()`

```{r data,warning=FALSE,message=FALSE,error=FALSE,results='hide',fig.height=10,fig.width=12}
#Loading Libraries

library(tidyverse)
library(readxl)
library(ggplot2)
library(tools)
source("process_hr_data_readable.R")
source('label_both_upper.R')
source('extract_h2o_model_name_by_position.R')
library(h2o)
library(lime)
library(rsample)
library(recipes)
library(PerformanceAnalytics)  # for skewness  

#Fetching Data

employee_attrition_tbl <- read_csv("datasets-1067-1925-WA_Fn-UseC_-HR-Employee-Attrition.csv")
definitions_raw_tbl    <- read_excel("data_definitions.xlsx", sheet = 1, col_names = FALSE)


#Creating Required Data
definitions_tbl <- definitions_raw_tbl %>% 
  fill(...1, .direction = "down") %>%
  filter(!is.na(...2)) %>%
  separate(...2, into = c("key", "value"), sep = " '", remove = TRUE) %>%
  rename(column_name = ...1) %>%
  mutate(key = as.numeric(key)) %>%
  mutate(value = value %>% str_replace(pattern = "'", replacement = "")) 

definitions_list <- definitions_tbl %>% 
  split(.$column_name) %>%
  map(~ select(., -column_name)) %>%
  map(~ mutate(., value = as_factor(value))) 

for (i in seq_along(definitions_list)) {
  list_name <- names(definitions_list)[i]
  colnames(definitions_list[[i]]) <- c(list_name, paste0(list_name, "_value"))
}

data_merged_tbl <- list(HR_Data = employee_attrition_tbl) %>%
  append(definitions_list, after = 1) %>%
  reduce(left_join) %>%
  select(-one_of(names(definitions_list))) %>%
  set_names(str_replace_all(names(.), pattern = "_value", replacement = "")) %>%
  select(sort(names(.)))

data_merged_tbl %>%
  mutate_if(is.character, as.factor) %>%
  select_if(is.factor) %>%
  map(levels)

data_processed_tbl <- data_merged_tbl %>%        
  mutate_if(is.character, as.factor) %>%
  mutate(
    BusinessTravel = BusinessTravel %>% fct_relevel("Non-Travel", 
                                                    "Travel_Rarely", 
                                                    "Travel_Frequently"),
    MaritalStatus  = MaritalStatus %>% fct_relevel("Single", 
                                                   "Married", 
                                                   "Divorced")
  )

data_processed_tbl %>% 
  select_if(is.factor) %>% 
  map(levels)

process_hr_data_readable(employee_attrition_tbl, definitions_raw_tbl)

employee_attrition_readable_tbl <- process_hr_data_readable(employee_attrition_tbl, definitions_raw_tbl)

# Split into test and train
set.seed(seed = 1113)
split_obj <- rsample::initial_split(employee_attrition_readable_tbl, prop = 0.85)

# Assign training and test data
train_readable_tbl <- training(split_obj)
test_readable_tbl  <- testing(split_obj)

# ML Preprocessing Recipe 
recipe_obj <- recipe(Attrition ~ ., data = train_readable_tbl) %>%
  step_zv(all_predictors()) %>%
  step_mutate_at(c("JobLevel", "StockOptionLevel"), fn = as.factor) %>% 
  prep()

train_tbl <- bake(recipe_obj, new_data = train_readable_tbl)
test_tbl  <- bake(recipe_obj, new_data = test_readable_tbl)

#Models

h2o.init()

split_h2o <- h2o.splitFrame(as.h2o(train_tbl), ratios = c(0.85), seed = 1122) 
train_h2o <- split_h2o[[1]] 
valid_h2o <- split_h2o[[2]] 
test_h2o  <- as.h2o(test_tbl) 


#Specifiy the response and predictor variables
y <- "Attrition"
x <- setdiff(names(train_h2o), y)


aml <- h2o.automl(x = x, y = y,
                  training_frame = train_h2o,
                  max_models = 20,
                  seed = 1, nfolds = 0)


# view leaderboard

lb <- aml@leaderboard
print(lb, n = nrow(lb))  # Print all rows instead of default (6 rows)


predictions_tbl <- h2o.predict(aml@leader, test_h2o)
predictions_tbl %>% as.tibble() %>% bind_cols(test_tbl %>% select(Attrition, EmployeeNumber))

automl_leader = aml@leader
explainer <- train_tbl %>%
  select(-Attrition) %>%
  lime(
    model           = automl_leader,
    bin_continuous  = TRUE,
    n_bins          = 4,
    quantile_bins   = TRUE
  )

explanation <- test_tbl %>%
  slice(1) %>%
  select(-Attrition) %>%
  lime::explain(
    explainer = explainer,
    n_labels   = 1,
    n_features = 8,
    n_permutations = 5000,
    kernel_width   = 0.8
  )
explanation<-explanation %>% 
  as.tibble()%>%
  filter(case == 1)

## Recreating plot_feature() 
type_pal <- c("Supports", "Contradicts")
ncol = 2

explanation$type <- factor(ifelse(sign(explanation$feature_weight) == 1, type_pal[1], type_pal[2]), levels = type_pal)
description <- paste0(explanation$case, "_", explanation[["label"]])
desc_width <- max(nchar(description)) + 1
description <- paste0(format(description, width = desc_width),explanation$feature_desc)
explanation$description <- factor(description, levels = description[order(abs(explanation$feature_weight))])
explanation$case <- factor(explanation$case, unique(explanation$case))
explanation$`Explanation fit` <- format(explanation$model_r2,digits = 2)
explanation$probability <- format(explanation$label_prob,digits = 2)
explanation$label <- factor(explanation$label, unique(explanation$label[order(explanation$label_prob,decreasing = TRUE)]))
ggplot(explanation) + facet_wrap(~case + label + probability + `Explanation fit`, labeller = label_both_upper,scales = "free_y", ncol = ncol)+
  geom_col(aes_(~description, ~feature_weight, fill = ~type)) + 
  coord_flip() + scale_fill_manual(values = c("steelblue","firebrick"), drop = FALSE) + 
  scale_x_discrete(labels = function(lab) substr(lab,desc_width + 1, nchar(lab))) + labs(y = "Weight", x = "Feature", fill = "")


## Recreating plot_explanation() 
 explanation <- test_tbl %>%
  slice(1:20)%>%
   select(-Attrition) %>%
   lime::explain(
     explainer = explainer,
     n_labels   = 1,
     n_features = 8,
     n_permutations = 5000,
     kernel_width   = 0.5
   )%>%
   as.tibble()
 
 explanation$feature_desc <- factor(explanation$feature_desc,levels = rev(unique(explanation$feature_desc[order(explanation$feature,explanation$feature_value)])))
 
 ggplot(explanation, aes_(~case, ~feature_desc)) + geom_tile(aes_(fill = ~feature_weight)) + 
   scale_x_discrete("Case", expand = c(0, 0)) + scale_y_discrete("Feature",expand = c(0, 0)) + scale_fill_gradient2("Feature\nweight",low = "firebrick", mid = "#f7f7f7", high = "steelblue") + 
   theme(panel.border = element_rect(fill = NA,colour = "grey60", size = 1), panel.grid = element_blank(), 
                        legend.position = "right", axis.text.x = element_text(angle = 45,hjust = 1, vjust = 1))+
   facet_wrap(~label)
```